name: CI build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' && github.ref != 'refs/heads/main' }}


jobs:
  build:
    runs-on: [ubuntu-latest]
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-docker-${{ hashFiles('**/*.yml') }}
          restore-keys: |
            ${{ runner.os }}-docker-
      - uses: docker
        run: docker build ./bugzilla-1-base